### ISSUE TITLE
Al realizar busquedas, no devuelve un valor del código postal correcto.

### ISSUE THREAD

**Issue by aalameda** [sigdeletras/buscacalles-cartociudad#1]
He realizado varias busquedas y el resultado del código postal parece estar mal 

![imagen](https://user-images.githubusercontent.com/19682177/101618187-ec679b00-3a11-11eb-9043-cab76ced16fb.png)

**Comment by sigdeletras** [comment]
Hola @aalameda 

He revisado el caso y efectivamente ocurre lo mismo con otras calles. Me han pasado email de soporte consulta@cnig.es para reportar este tipo de cuestiones.

Gracias por el isuue
